/**
 * Better Auth Database Schema
 * 
 * This file is AUTO-GENERATED by Better Auth CLI.
 * DO NOT EDIT MANUALLY - regenerate using:
 * npx @better-auth/cli@latest generate --config ./better-auth.config.ts --output ./lib/db/auth.schema.ts
 * 
 * Placeholder file - will be generated when you run the CLI command
 */

// This is a placeholder. Run the Better Auth CLI to generate the actual schema.
// The CLI will create tables for: user, session, account, verification, twoFactor, etc.

export const placeholder = {};
