import { defineCloudflareConfig } from "@opennextjs/cloudflare";

export default defineCloudflareConfig({
  minify: true,
  external: [
    "pg-cloudflare",
    "pgpass",
    "pg",
    "pg-native",
    "pg-pool",
    "pg-protocol",
    "pg-types",
    "better-sqlite3",
    "mysql2",
    "oracledb",
    "tedious",
    "sqlite3",
    "@vscode/sqlite3",
    "kysely",
    "@supabase/auth-helpers-nextjs",
    "@supabase/auth-ui-react",
    "@supabase/auth-ui-shared",
    "@vercel/node",
    "@vercel/remix-builder",
    "@vercel/og",
    "esbuild",
    "swc",
    "async_hooks",
    "buffer",
    "crypto",
    "events",
    "fs",
    "http",
    "https",
    "os",
    "path",
    "stream",
    "util",
    "vm",
    "url",
    "zlib",
    "string_decoder",
    "tls",
    "net"
  ],
});
