# Configuración optimizada para Cloudflare Pages + Next.js + Supabase
name = "nexdrak-site"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

# Variables de entorno para Supabase
[vars]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

# Configuración para Node.js compatibility
[env.production]
compatibility_flags = ["nodejs_compat"]