name = "nex-website"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Ensure variables are treated correctly (though they should be set in dashboard)
[vars]
# NODE_ENV = "production"
