# Optimized configuration for Cloudflare Pages + Next.js + Supabase
name = "nexdrak-site"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
cwd = "."

# Environment variables for Supabase
[vars]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

# Configuration for Node.js compatibility
[env.production]
compatibility_flags = ["nodejs_compat"]