# Configuración para Cloudflare Pages
name = "nexdrak-site"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "modules"

# Configuración específica para Next.js en Cloudflare Pages
[[rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]
fallthrough = true

# Configuración para rutas de API
[[env.production.routes]]
pattern = "/api/*"
zone_name = ""
custom_domain = true

[env.production]
compatibility_flags = ["nodejs_compat"]